### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined with ignoreClass option

### ISSUE THREAD

**Issue by dmnsgn** [posthtml/posthtml-webp#14]
It happens only when using the ignoreClass option and I assume when image doesn't have a class attribute. It looks like the check below default to `|| []` in the wrong place:

https://github.com/posthtml/posthtml-webp/blob/e1248b4e70cd013338a55abb225e6692ee19e161/lib/index.js#L23-L25

A fix could be:
```js
// from
var classes = imgNode.attrs && imgNode.attrs.class && (imgNode.attrs.class.split(' ') || [])

// to
var classes = (imgNode.attrs && imgNode.attrs.class && imgNode.attrs.class.split(' ')) || []
```

**Comment by Scrum** [comment]
@dmnsgn Hi, sorry for the long answer, a lot of work piled up. Feel free with regard to PR, any contribution is very much appreciated

**Comment by dmnsgn** [comment]
No worries, created PR and updated tests here #15
