### ISSUE TITLE
Couple of proposal

### ISSUE THREAD

**Issue by ahmadalfy** [posthtml/posthtml-webp#9]
First, thank you so much for this awesome package. I have got a couple of proposals I would like to share with you and let me know if you're interested in including it. I would love to contribute.

1- Add the option to ignore files by extensions. In my case, I don't want `SVG` to be transformed and ignoring it by class isn't convenient.
2- Add the option to check if a webp version of the image already exists or not. If it exists, proceed and make the necessary transformation. If not, ignore it.

Thank you again

**Comment by Scrum** [comment]
@ahmadalfy  Hi, we are glad that our product is suitable for anyone. 

We have a positive attitude to suggestions and contributions, you can feel free in this regard.

Your suggestions sound good. Let me know if you need our help

**Comment by ahmadalfy** [comment]
Submitted PR for the first feature #10

**Comment by ahmadalfy** [comment]
Let me close this as it's not an issue and will follow on the PRs
